{"name": "test_login_registered_user", "status": "broken", "statusDetails": {"message": "OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.", "trace": "self = <tests.test_login.TestUserLogin object at 0x10297feb0>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"da673780985ba5e3bf9d4eee3af82afc\")>\n\n    @allure.story('Login with registered user credentials')\n    @allure.step('Login with registered user credentials')\n    def test_login_registered_user(self, driver):\n        my_account_page = MyAccountPage(driver)\n        my_account_page.open_my_account_page()\n    \n    \n        username = \"Veronika Stelmax\"\n        password = \"Ника1603!!!\"\n        my_account_page.login(username, password)\n    \n    \n        assert my_account_page.is_user_logged_in(), \"Пользователь не был успешно залогинен\"\n>       input()\n\ntests/test_login.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <_pytest.capture.DontReadFromInput object at 0x102028f70>, size = -1\n\n    def read(self, size: int = -1) -> str:\n>       raise OSError(\n            \"pytest: reading from stdin while output is captured!  Consider using `-s`.\"\n        )\nE       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.\n\n/opt/miniconda3/lib/python3.9/site-packages/_pytest/capture.py:207: OSError"}, "steps": [{"name": "Login with registered user credentials", "status": "broken", "statusDetails": {"message": "OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.\n", "trace": "  File \"/opt/miniconda3/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/macbooknikakrasivaya/PycharmProjects/2.7/pythonProjectFinal/tests/test_login.py\", line 28, in test_login_registered_user\n    input()\n  File \"/opt/miniconda3/lib/python3.9/site-packages/_pytest/capture.py\", line 207, in read\n    raise OSError(\n"}, "parameters": [{"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"da673780985ba5e3bf9d4eee3af82afc\")>"}], "start": 1717407701567, "stop": 1717407702612}], "start": 1717407701567, "stop": 1717407702614, "uuid": "66185b6b-bdd7-402f-834d-59916697930d", "historyId": "084add7f46ec095e76e51a348a26fb06", "testCaseId": "084add7f46ec095e76e51a348a26fb06", "fullName": "tests.test_login.TestUserLogin#test_login_registered_user", "labels": [{"name": "feature", "value": "User Login"}, {"name": "story", "value": "Login with registered user credentials"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MacBook-Air-MacBook.local"}, {"name": "thread", "value": "7022-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}